controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\PublicController::showHome

app_login:
    path: /login
    controller: App\Controller\UserSecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\UserSecurityController::logout

formations:
    path: /formations
    controller: App\Controller\PublicController::showFormations

forum:
    path: /forum
    controller: App\Controller\PublicController::showForum

store:
    path: /store
    controller: App\Controller\PublicController::showStore

blog:
    path: /blog
    controller: App\Controller\PublicController::showBlog

connexion:
    path: /connexion
    controller: App\Controller\PublicController::showConnexion

mapsite:
    path: /mapsite
    controller: App\Controller\PublicController::showMapsite

contact:
    path: /contact
    controller: App\Controller\PublicController::showContact

valonauteinc:
    path: /valonauteinc
    controller: App\Controller\PublicController::showValonauteinc

careers:
    path: /careers
    controller: App\Controller\PublicController::showCareers

cgu:
    path: /cgu
    controller: App\Controller\PublicController::showCgu

rgpd:
    path: /rgpd
    controller: App\Controller\PublicController::showRgpd

user_home:
    path: /user/home
    controller: App\Controller\UserSecurityController::showHome

dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminSecurityController::showDashboard

show_category:
    path: /category/show
    controller: App\Controller\CategoryController::showCategory

create_category:
    path: /admin/category/create
    controller: App\Controller\CategoryController::createCategory

update_category:
    path: /admin/category/update/{id}
    controller: App\Controller\CategoryController::updateCategory

delete_category:
    path: /admin/category/delete/{id}
    controller: App\Controller\CategoryController::deleteCategory

show_product:
    path: /product/show
    controller: App\Controller\ProductController::showProducts

create_product:
    path: /admin/product/create
    controller: App\Controller\ProductController::createproduct

update_product:
    path: /admin/product/update/{id}
    controller: App\Controller\ProductController::updateProduct

delete_product:
    path: /admin/product/delete/{id}
    controller: App\Controller\ProductController::deleteProduct

product_front:
    path: /product/{id}
    controller: App\Controller\ProductController::showProductFront

create_article:
    path: /admin/article/create
    controller: App\Controller\ArticleController::createArticle

show_article:
    path: /articles/show
    controller: App\Controller\ArticleController::showArticles

update_article:
    path: /admin/article/update/{id}
    controller: App\Controller\ArticleController::updateArticle

delete_article:
    path: /admin/article/delete/{id}
    controller: App\Controller\ArticleController::deleteArticle

cart_add:
    path: /cart/add/{id}
    controller: App\Controller\CartController::add

