<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxOAqVD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxOAqVD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxOAqVD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxOAqVD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxOAqVD\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxOAqVD',
    'container.build_id' => 'fe757f5e',
    'container.build_time' => 1687384310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxOAqVD');
