<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGRxB20R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGRxB20R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGRxB20R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGRxB20R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGRxB20R\App_KernelDevDebugContainer([
    'container.build_hash' => 'GRxB20R',
    'container.build_id' => '8483fe9c',
    'container.build_time' => 1687083394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGRxB20R');
