<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSX3okt0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSX3okt0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSX3okt0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSX3okt0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSX3okt0\App_KernelDevDebugContainer([
    'container.build_hash' => 'SX3okt0',
    'container.build_id' => '75ee6e9e',
    'container.build_time' => 1686416337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSX3okt0');
